#!/bin/sh
root_path=/home/sunchao/work/fg3_test/run/mct_c_coupler_test

rm *.o *.mod *.so

mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.share -I/data/sunchao/fg3_test/FG3/models/drv/shr_mct -I/data/sunchao/fg3_test/FG3/models/drv/shr -I/data/sunchao/fg3_test/FG3/models/dead_share -I/data/sunchao/fg3_test/FG3/models/csm_share/shr -I/data/sunchao/fg3_test/FG3/models/utils/esmf_wrf_timemgr -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC -g -traceback -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DNUM_COMP_INST_ROF=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   /data/sunchao/fg3_test/FG3/models/csm_share/shr/shr_kind_mod.F90

mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.share -I/data/sunchao/fg3_test/FG3/models/drv/shr_mct -I/data/sunchao/fg3_test/FG3/models/drv/shr -I/data/sunchao/fg3_test/FG3/models/dead_share -I/data/sunchao/fg3_test/FG3/models/csm_share/shr -I/data/sunchao/fg3_test/FG3/models/utils/esmf_wrf_timemgr -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC -g -traceback -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DNUM_COMP_INST_ROF=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   /data/sunchao/fg3_test/FG3/models/csm_share/shr/shr_const_mod.F90

mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.share -I/data/sunchao/fg3_test/FG3/models/drv/shr_mct -I/data/sunchao/fg3_test/FG3/models/drv/shr -I/data/sunchao/fg3_test/FG3/models/dead_share -I/data/sunchao/fg3_test/FG3/models/csm_share/shr -I/data/sunchao/fg3_test/FG3/models/utils/esmf_wrf_timemgr -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC -g -traceback -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DNUM_COMP_INST_ROF=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   /data/sunchao/fg3_test/FG3/models/csm_share/shr/shr_log_mod.F90

mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.share -I/data/sunchao/fg3_test/FG3/models/drv/shr_mct -I/data/sunchao/fg3_test/FG3/models/drv/shr -I/data/sunchao/fg3_test/FG3/models/dead_share -I/data/sunchao/fg3_test/FG3/models/csm_share/shr -I/data/sunchao/fg3_test/FG3/models/utils/esmf_wrf_timemgr -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC -g -traceback -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DNUM_COMP_INST_ROF=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   /data/sunchao/fg3_test/FG3/models/csm_share/shr/shr_mpi_mod.F90

mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.share -I/data/sunchao/fg3_test/FG3/models/drv/shr_mct -I/data/sunchao/fg3_test/FG3/models/drv/shr -I/data/sunchao/fg3_test/FG3/models/dead_share -I/data/sunchao/fg3_test/FG3/models/csm_share/shr -I/data/sunchao/fg3_test/FG3/models/utils/esmf_wrf_timemgr -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC -g -traceback -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DNUM_COMP_INST_ROF=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   /data/sunchao/fg3_test/FG3/models/csm_share/shr/shr_sys_mod.F90


mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.share -I/data/sunchao/fg3_test/FG3/models/drv/shr_mct -I/data/sunchao/fg3_test/FG3/models/drv/shr -I/data/sunchao/fg3_test/FG3/models/dead_share -I/data/sunchao/fg3_test/FG3/models/csm_share/shr -I/data/sunchao/fg3_test/FG3/models/utils/esmf_wrf_timemgr -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC -g -traceback -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DNUM_COMP_INST_ROF=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   /data/sunchao/fg3_test/FG3/models/csm_share/shr/shr_flux_mod.F90

mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/atm/obj -I/$root_path/bld/lnd/obj -I/$root_path/bld/ice/obj -I/$root_path/bld/ocn/obj -I/$root_path/bld/glc/obj -I/$root_path/bld/rof/obj -I/$root_path/bld/wav/obj -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.drv -I/data/sunchao/fg3_test/FG3/models/drv/driver -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC  -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   atmocn_flux_ccpl_kinds.F90

mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/atm/obj -I/$root_path/bld/lnd/obj -I/$root_path/bld/ice/obj -I/$root_path/bld/ocn/obj -I/$root_path/bld/glc/obj -I/$root_path/bld/rof/obj -I/$root_path/bld/wav/obj -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.drv -I/data/sunchao/fg3_test/FG3/models/drv/driver -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC  -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   atmocn_flux_ccpl_coupling.F90

mpiifort  -c -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/atm/obj -I/$root_path/bld/lnd/obj -I/$root_path/bld/ice/obj -I/$root_path/bld/ocn/obj -I/$root_path/bld/glc/obj -I/$root_path/bld/rof/obj -I/$root_path/bld/wav/obj -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.drv -I/data/sunchao/fg3_test/FG3/models/drv/driver -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC  -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free   atmocn_flux_ccpl_mod.F90

mpiifort atmocn_flux_ccpl_mod.o atmocn_flux_ccpl_coupling.o atmocn_flux_ccpl_kinds.o -I.  -I/$root_path/bld/pio -I/opt/netCDF-intel15-without-hdf5/include -I/opt/intel/impi/3.2.2.006/bin64/include -I/$root_path/bld/atm/obj -I/$root_path/bld/lnd/obj -I/$root_path/bld/ice/obj -I/$root_path/bld/ocn/obj -I/$root_path/bld/glc/obj -I/$root_path/bld/rof/obj -I/$root_path/bld/wav/obj -I/$root_path/bld/mct/mct -I/$root_path/bld/mct/mpeu -I/$root_path/bld/pio -I/$root_path/bld/gptl -I/data/sunchao/fg3_test/FG3/models/utils/pio -I/$root_path/bld/lib/include -I. -I/$root_path/SourceMods/src.drv -I/data/sunchao/fg3_test/FG3/models/drv/driver -I/$root_path/bld/lib/include  -O2 -fp-model precise -convert big_endian -assume byterecl -fp-speculation=safe -no-vec -no-simd -FR -mp1 -zero -fPIC  -DNUM_COMP_INST_ATM=1 -DNUM_COMP_INST_LND=1 -DNUM_COMP_INST_OCN=1 -DNUM_COMP_INST_ICE=1 -DNUM_COMP_INST_GLC=1 -DNUM_COMP_INST_WAV=1 -DLINUX  -DMCT_INTERFACE -DHAVE_MPI -DFORTRANUNDERSCORE -DNO_R16 -DLINUX -DCPRINTEL  -DHAVE_SLASHPROC -free  -shared -o libatmocn_flux.so

cp -rf libatmocn_flux.so $root_path/run/CCPL_dir/libs/external_modules/
